//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yeniAkademiFitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        public int uyeID { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public string uyeTelefon { get; set; }
        public string uyeTCKN { get; set; }
        public Nullable<System.DateTime> uyeKayitTarih { get; set; }
        public Nullable<System.DateTime> uyeBitisTarih { get; set; }
        public string uyeUyelikTipi { get; set; }
        public string uyeBorcDurumu { get; set; }
    }
}
